source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

target 'SCFramework' do

    pod 'AFNetworking', '~> 3.2.0'
    pod 'SDWebImage', '~> 4.4.0'
    pod 'Mantle', '~> 2.1.0'
    pod 'Masonry', '~> 1.1.0'
    pod 'ReactiveObjC', '~> 3.1.0'

    pod 'MBProgressHUD', '~> 0.9.0'

    pod 'FMDB', '~> 2.7.0'

    pod 'SSKeychain', '~> 1.2.0'

end
