platform :ios, "6.0"
pod 'AFNetworking', '~> 2.2.3'
pod 'SDWebImage', '~> 3.6'
pod 'MBProgressHUD', '~> 0.8'
pod 'FMDB', '~> 2.2'
pod 'ReactiveCocoa', '~> 2.3'
pod 'Masonry', '~> 0.4.0'
pod 'JSONModel', '~> 0.13.0'
pod 'pop', '~> 1.0.4'